spring:
  cloud:
    gateway:
      routes:
        - id: authService
          uri: lb://authService
          predicates:
            - Path=/api/v1/campusConnect/auth/**
          filters:
            - StripPrefix=2

        - id: chatService
          uri: lb://chatService
          predicates:
            - Path=/api/v1/campusConnect/chat/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
            
        - id: alumniService
          uri: lb://aluminiService
          predicates:
            - Path=/api/v1/campusConnect/alumni/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: classroomService
          uri: lb://classroomService
          predicates:
            - Path=/api/v1/campusConnect/classroom/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: forumService
          uri: lb://forumService
          predicates:
            - Path=/api/v1/campusConnect/forum/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: gamificationService
          uri: lb://gamificationService
          predicates:
            - Path=/api/v1/campusConnect/gamification/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: opportunityService
          uri: lb://opportunityService
          predicates:
            - Path=/api/v1/campusConnect/opportunity/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

server:
  port: 8080

jwt:
  secretKey: jajfkfahancfhaihsdunnfakdjbfdfhjakjj

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.campusConnect.apiGateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
