spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/campusConnect

server:
  servlet:
    context-path: /campusConnect/chat
  port: 8082

userService:
  base:
    url: http://localhost:8081/campusConnect/user/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
