spring:
  data:
    mongodb:
      uri: mongodb+srv://deepakbarajati2004_db_user:4llkudx5s0K8LsN5@campusconnnect.ufyx2h6.mongodb.net/
server:
  servlet:
    context-path: /campusConnect/chat
  port: 8082

userService:
  base:
    url: http://localhost:8081/campusConnect/user/
