spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/campusConnect?authSource=admin&retryWrites=false

server:
  servlet:
    context-path: /campusConnect/chat
  port: 8082

userService:
  base:
    url: http://localhost:8081/campusConnect/user
