spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campusConnect
    username: postgres
    password: 52616a616e69
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /api/v1
  port: 8086
